-- Uses the database, schema, warehouse and role in the CLI connection.
-- Requires ORDERS from the S3 integration exercise.
SELECT CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_WAREHOUSE(), CURRENT_ROLE();
SELECT ORDER_ID, ORDER_DATE, CUSTOMER_NAME, STATUS, ORDER_TOTAL
FROM ORDERS ORDER BY ORDER_ID LIMIT 20;
SELECT STATUS, COUNT(*) AS ORDER_COUNT, SUM(ORDER_TOTAL) AS TOTAL_AMOUNT
FROM ORDERS GROUP BY STATUS ORDER BY STATUS;
